### ISSUE TITLE
Missing schema declaration

### ISSUE THREAD

**Issue by raffazizzi** [jeschollaert/Diamondback-Encoding#2]
Hi there,

Your file is missing a schema declaration, so it's not getting validated! There are a few issues in your TEI that you're not seeing because Atom is not able to validate it.

Make sure the first lines of your file are:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/Vault/P5/current/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/Vault/P5/current/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
```

**Comment by jeschollaert** [comment]
Thank you for catching that!! I'm so sorry that you went through the trouble to look over these files, with their many errors-my apologies!

**Comment by raffazizzi** [comment]
No worries, I've been going through everyone's :smile:
